---
title: "Disney mapping with React"
type: "exercise"
description: "Use .map to dynamically display a list of movies and songs"
tags: "React, stateful components, nested components"
ignore:
- "node_modules/"
- "disney-mapping-with-react.md"
---
